//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveASpot.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveASpot.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        internal static string AddSpotToCartSuccess {
            get {
                return ResourceManager.GetString("AddSpotToCartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin in current application is exists..
        /// </summary>
        internal static string AdminExists {
            get {
                return ResourceManager.GetString("AdminExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ConfirmPasswordDisplay {
            get {
                return ResourceManager.GetString("ConfirmPasswordDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        internal static string ConfirmPasswordErrorMessageDisplay {
            get {
                return ResourceManager.GetString("ConfirmPasswordErrorMessageDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name.
        /// </summary>
        internal static string CustomerNameDisplay {
            get {
                return ResourceManager.GetString("CustomerNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string CustomersTabTitle {
            get {
                return ResourceManager.GetString("CustomersTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        internal static string EmailDisplay {
            get {
                return ResourceManager.GetString("EmailDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        internal static string InvalidOldOrNewPassword {
            get {
                return ResourceManager.GetString("InvalidOldOrNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot price should be greate than 0.01 and less than 4000000.
        /// </summary>
        internal static string InvalidSpotPriceValue {
            get {
                return ResourceManager.GetString("InvalidSpotPriceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid spedified user email..
        /// </summary>
        internal static string InvalidUserEmail {
            get {
                return ResourceManager.GetString("InvalidUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid specified username..
        /// </summary>
        internal static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        internal static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid specified user password. Password should be greater than {0} and less than {1}..
        /// </summary>
        internal static string InvalidUserPassword {
            get {
                return ResourceManager.GetString("InvalidUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string MapTabTitle {
            get {
                return ResourceManager.GetString("MapTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many spots to display in this region. Please zoom in..
        /// </summary>
        internal static string MuchSpotsInSquare {
            get {
                return ResourceManager.GetString("MuchSpotsInSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not recognize json format when loading Spot document.
        /// </summary>
        internal static string NotRecognizeJsonForSpot {
            get {
                return ResourceManager.GetString("NotRecognizeJsonForSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create object from loaded Spot document.
        /// </summary>
        internal static string NotRecognizeObjectForSpot {
            get {
                return ResourceManager.GetString("NotRecognizeObjectForSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcels.
        /// </summary>
        internal static string ParcelsAccordionGroupTitle {
            get {
                return ResourceManager.GetString("ParcelsAccordionGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For performance purposes we display only those spots of the selected phase that are located within the current region..
        /// </summary>
        internal static string PartSpotsInSquare {
            get {
                return ResourceManager.GetString("PartSpotsInSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordDisplay {
            get {
                return ResourceManager.GetString("PasswordDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phases.
        /// </summary>
        internal static string PhasesAccordionGroupTitle {
            get {
                return ResourceManager.GetString("PhasesAccordionGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcels &amp; Spots.
        /// </summary>
        internal static string PhasesAndParcelsTabTitle {
            get {
                return ResourceManager.GetString("PhasesAndParcelsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        internal static string RememberMeDisplay {
            get {
                return ResourceManager.GetString("RememberMeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string SponsorCompanyNameDisplay {
            get {
                return ResourceManager.GetString("SponsorCompanyNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo Url.
        /// </summary>
        internal static string SponsorLogoDisplay {
            get {
                return ResourceManager.GetString("SponsorLogoDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence.
        /// </summary>
        internal static string SponsorSentenceDisplay {
            get {
                return ResourceManager.GetString("SponsorSentenceDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsors.
        /// </summary>
        internal static string SponsorsTabTitle {
            get {
                return ResourceManager.GetString("SponsorsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string SponsorUrlDisplay {
            get {
                return ResourceManager.GetString("SponsorUrlDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot not available..
        /// </summary>
        internal static string SpotNotAvailableToAddToCart {
            get {
                return ResourceManager.GetString("SpotNotAvailableToAddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot not found, please refresh spots and try again later..
        /// </summary>
        internal static string SpotNotFound {
            get {
                return ResourceManager.GetString("SpotNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot price.
        /// </summary>
        internal static string SpotPrice {
            get {
                return ResourceManager.GetString("SpotPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spots.
        /// </summary>
        internal static string SpotsAccordingGroupTitle {
            get {
                return ResourceManager.GetString("SpotsAccordingGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spots found for the current region..
        /// </summary>
        internal static string SpotsInCurrentRegionNotFound {
            get {
                return ResourceManager.GetString("SpotsInCurrentRegionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spots displayed since we cannot retrieve the spots of the selected phase..
        /// </summary>
        internal static string UnknowBehavior {
            get {
                return ResourceManager.GetString("UnknowBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Phases &amp; Parcels.
        /// </summary>
        internal static string UploadPhasesAndParcelsAccordionGroupTitle {
            get {
                return ResourceManager.GetString("UploadPhasesAndParcelsAccordionGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with same name exists..
        /// </summary>
        internal static string UserExistsError {
            get {
                return ResourceManager.GetString("UserExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string UserNameDisplay {
            get {
                return ResourceManager.GetString("UserNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not exists..
        /// </summary>
        internal static string UserNotExistsError {
            get {
                return ResourceManager.GetString("UserNotExistsError", resourceCulture);
            }
        }
    }
}
